### PR TITLE
add org attribute to LimeSurvey class

### PR DESCRIPTION
**Pull request by johnlee2104**
So far only added `self.org` attribute and modified slightly the `plot` function so that the plot title include organization name. I am not sure if I should modify the test too to test this...

### CODE REVIEW

**Comment by fudw** [comment]
It would be nice to add this attribute to existing tests and make sure it works as intended. 

Another three things:

1. It should be checked and enforced that there are only several allowed inputs, and they should be pre-determined and consistently used, i.e. "MPI", "HH" or whatever, in order to prevent messy inputs like "mpi" and "MPI" both existing at the same time. Perhaps @lheckmann can dictate what the allowed ones should be. Then one should write several `assert` statements to make sure the input is among these.
2. In the `export_to_file` method in `survey.py`, currently it asks for a user input for the org name. This should be updated to take the `self.org` attribute instead if it is available and ask for it only if `self.org` is `None`. 
3. Yet another consequence of this comes about when importing the exported data from another org, which takes place in the `read_responses` method. The `self.org` attribute should be automatically inferred and updated there from the first column of the imported DataFrame.

@johnlee2104  Can you please implement these things? If anything is unclear or you need help, feel free to let me know.

**Comment by lheckmann** [comment]
And here are the short cuts to use:

"MPS", "Hemholtz", "Leibniz", "TUM" and "N2". (if possible, but I can make another small issue for that it would be great if the 2 in N2 can be upper case when printing it in a title, but that's a small addition)

@Tianbe the same for the color schemes.

**Comment by fudw** [comment]
@johnlee2104 How are things coming along? Do you need help with any of the things I mentioned above? Now that a new issue has been assign to you, I'm happy to take over this PR if you have too much to work on.

**Comment by johnlee2104** [comment]
> @johnlee2104 How are things coming along? Do you need help with any of the things I mentioned above? Now that a new issue has been assign to you, I'm happy to take over this PR if you have too much to work on.

Hey @fudw , sorry for the late reply! That's very nice of you to offer, I think it would be great if you take over this PR since you're also probably more familiar with all the other functions and how to incorporate this into them. Thank you!

**Comment by fudw** [comment]
Implemented additional changes. Added new tests. Rebased from main.

So far, the org attribute is still kept optional at instantiation, and only hard required when exporting aggregate data, to ensure compatibility with existing scripts. If this is to be made mandatory in the future, one can eliminate a number of redundant checks on the conformity of the org attribute outside of `__init__` with pre-defined org names.

**Comment by lheckmann** [comment]
Thank you for implementing everything so fast!
For the error message:
`ValueError: Must specify organization name as one of ['MPS', 'Helmholtz', 'Leibniz', 'TUM', 'N2']`
I would change it to something like
`ValueError: Must specify organization name as org argument when initializing the limesurvey object as one of ['MPS', 'Helmholtz', 'Leibniz', 'TUM', 'N2']`
so the user does not try to do it in the plot function.

For read_responses: I though we add org when doing the initialization of the limesurvey object. I do not understand the functionality here.
Also I do not get an error message when not defining it, which I think is fine. Just so you know,

**Comment by fudw** [comment]
> Must specify organization name as org argument when initializing the limesurvey object

I was thinking that it would be frustrating that a user wants to make a plot after doing some processing and is told to re-initialize and re-do everything, so one should be allowed to add the org attribute at any point. But because it's as simple as `survey.org = "MPS"`, I wasn't sure whether it's worth writing a function just for this, or rather simply mention this in the wiki.

> For read_responses: I though we add org when doing the initialization of the limesurvey object. I do not understand the functionality here. 

I was under the impression that "Would be nice to catch the cases where no org is defined" meant there will be occasions where it is not defined at initialization, "has to be stated when loading the framework" meant when reading in the exported CSV. Or did I misunderstand you?

> Also I do not get an error message when not defining it

It only raises an error when it is absent as an arg to `read_responses` AND it cannot be inferred from the exported CSV (first column named "organization" being empty)

**Comment by lheckmann** [comment]
> I was thinking that it would be frustrating that a user wants to make a plot after doing some processing and is told to re-initialize and re-do everything, so one should be allowed to add the org attribute at any point. But because it's as simple as `survey.org = "MPS"`, I wasn't sure whether it's worth writing a function just for this, or rather simply mention this in the wiki.
> 

Ah okay, yes I think it is enough to just mention `survey.org = "MPS"` in the wiki.

> I was under the impression that "Would be nice to catch the cases where no org is defined" meant there will be occasions where it is not defined at initialization, "has to be stated when loading the framework" meant when reading in the exported CSV. Or did I misunderstand you?
> 

I just meant in the export function since it gave a unclear error message. But now it just gives an empty string for the export org column, so that should also be fine. The users should realize then that nothing was specified.


> 
> It only raises an error when it is absent as an arg to `read_responses` AND it cannot be inferred from the exported CSV (first column named "organization" being empty)

Ah okay good.

**Comment by lheckmann** [comment]
Then we should be ready to merge right?

**Comment by fudw** [comment]
Your comment reminds me that it's actually best a method for setting the org attribute is provided, given that the allowed input is strictly limited. This allows me to reduce some redundancy in checks on the content of the attribute. Also fixed a bug where `np.isnan` doesn't like strings; replaced with `pd.isna`.

Now it's ready to be merged.

**Comment by lheckmann** [comment]
Good point! Thank you for all of the work :)

**Pull request merged**
