### PR TITLE
69 Helper functions for exporting and importing aggregate data

### PR DESCRIPTION
**Pull request by fudw**
## Description

- This PR is for Issue #69 
- Implemented two helper functions as LimeSurvey class methods for exporting aggregate data for specific question to csv file and importing such data from csv file
- Tested manually on default test questions without problem

## Checklist

- [x] I created an issue and discussed solutions with others.
- [x] I wrote tests or updated tests regarding my changes.
- [x] I follow the style guidelines of this project.
- [x] I have commented my code. So, other can understand what I did.
- [x] I checked if all tests passing after my changes.

## PR review

Anyone in the community is free to review the PR once the tests have passed.

- [x] Add labels and milestones to the PR so it can be classified.
- [x] Check that all items from the **checklist** are resolved.
- [x] Is this pull request ready for review?

### CODE REVIEW

**Comment by fudw** [comment]
@lheckmann Updated and ready. Please try it out and let me know if you would like something changed.

**Comment by lheckmann** [comment]
Now it looks nice! I get the same results when using single questions, but random when comparing questions!

One more details to add:

Can we have it as optional which questions are removed? 
(not the free text, they should always be removed, but the institute one e.g.). Then the responsibility is with the one exporting and I prefer that then if it's automatic in the code.

**Comment by lheckmann** [comment]
If I specify drop_column, can you check that the questions exist and otherwise give an error output message saying that the specified question does not exist? 
At the moment it gives the nomal python errors ("KeyError: "['2'] not found in axis").

**Comment by lheckmann** [comment]
This year 'A2' is always the institute question, but that might change maybe in the next years.
So I would either remove the 
" if "A2" in data.columns:
            columns_to_drop.append("A2")"
part and just let the user use the drop_columns parameter.

Or we let the user define a drop_institute question and use the drop_columns for additional questions that should be dropped.

**Comment by fudw** [comment]
Everything updated and should be ready now.

**Pull request merged**
