### PR TITLE
17-multiple-choice-plots-function

### PR DESCRIPTION
**Pull request by fudw**
Created plotting function as specified in #17 

While I have manually tested it on all questions of this type in the 2021 survey, how should I write a test file for it?

### CODE REVIEW

**Comment by fudw** [comment]
> I guess we should also merge this with the main branch, before we start to work on the LimeSurvey class. Otherwise we can not access the plotting functions
@Tianbe 
This function will need input about structure and data from init and a pre-processing function, which I will try to get done asap. If you are working on the plot function in the LimeSurvey class, feel free to make some dummy function as place holders for the time being.

**Comment by fudw** [comment]
## Description

- Created plot_multiple_choice module.
- Implemented make_bar_plot_for_multiple_choice_question function and related helper functions
- Implemented test for make_bar_plot_for_multiple_choice_question
- Updated tests/common.py to include read_responses step, which is used for more than one test
- Implemented temporary replacement function to reproduce output of get_responses_counts method, which is still work in progress, based on description and expectation


## Checklist

- [ ] I created an issue and discussed solutions with others.
- [ ] I wrote tests or updated tests regarding my changes.
- [ ] I follow the style guidelines of this project.
- [ ] I have commented my code. So, other can understand what I did.
- [ ] I checked if all tests passing after my changes.

## PR review

Anyone in the community is free to review the PR once the tests have passed.

- [ ] Add labels and milestones to the PR so it can be classified.
- [ ] Check that all items from the **checklist** are resolved.
- [ ] Is this pull request ready for review?

**Comment by fudw** [comment]
@rguliev This PR is now ready for review.

**Comment by rguliev** [comment]
@fudw Thanks! I will add minor fixes and merge it.

**Pull request merged**
