### PR TITLE
18 single vs multiple choice question

### PR DESCRIPTION
**Pull request by TheFlike**
## Description

This is a big one, sorry, but it was necessary.
It adds the comparison between multiple-choice and single-choice questions and a deposit of shared functions used for comparison plots.

 Following changes are done:
1. added the comparison (multiple-choice, single-choice) to the `check_plot_implemented()` function in survey.py,
2. changed the calculation of the `plot_data_list` in `create_comparison_data()`: now only pandas data frames are used and the change away from pandas is pushed deeper into the comparison_plot files. --> This required small changes in simple_comparison.py
3. Flake8 made me create the function `plot_comparison` which is now called from plot if argument compare_with is used. Everything works the same as before. But plot is now less "complicated", meaning it has less ifs elifs and elses.
4. created the file comparison_shared_functions.py which hosts functions that are used by more than one comparison plot. Every time I reuse a function for the first time, I will move it there.
5. created the file multiple_simple_comparison.py for the calculation of comparison between multiple-choice and single-choice Questions
6. since word wrapping for the x-axis was wanted I added the library textwrap to the repository, I hope it is possible to add it to the environment? Else I would have to write a word-wrapping function on my own, which seems redundant.

## Checklist

- [x] I created an issue and discussed solutions with others.
- [x] I wrote tests or updated tests regarding my changes.
- [x] I follow the style guidelines of this project.
- [x] I have commented my code. So, other can understand what I did.
- [x] I checked if all tests passing after my changes.

## PR review

Anyone in the community is free to review the PR once the tests have passed.

- [x] Add labels and milestones to the PR so it can be classified.
- [x] Check that all items from the **checklist** are resolved.
- [x] Is this pull request ready for review?

### CODE REVIEW

**Comment by lheckmann** [comment]
Thanks for the nice work.

A few things I spotted:
- Can we add % signs to the bars?
- What do the bar positions do? There does not seem to be a space between total and other bars if you put bar_positions=[0, 1.5, 2.5, 4.5]
- This might not be a problem in the big data set, but I think it looks a bit weird to just have a space for when we do not have any answers for one of the bars. Do you have an idea how to circumvent it? Maybe just put a thin line to show where the bar would be and that it is 0?
- Do you remember what we agreed on for the label sizes? Guess that should be handled at some point because now there are too small in basically all plot types. Otherwise I'll contact Rustam and Dawei to ask.
- Yes to the text wrap, we need it. Can we add it in a way that it is installed automatically with the package?

**Comment by lheckmann** [comment]
And another question (also for the normal comp plots):
"I don't know does not exist for this question" 
is always printed. But also should it be removed automatically??

**Comment by lheckmann** [comment]
> 

But should we filter them out automatically? Shouldn't it be up to the user to decide if to include them?

**Comment by lheckmann** [comment]
- bar position: I think we only need it for positioning inside a bar group (that's where the total is right?). 

- 0 count bars: I would not filter them out, might also confuse people. Just add a line that shows that there are basically no answer, but we considered the group.

- calculate_aspect_ratio=True, yes should be standard True I would say. We just have to put it clearly in the documentation that if they want to change the fig size, they have to set it to False.

**Comment by TheFlike** [comment]
> About the "I don't know":
> 
> But should we filter them out automatically? Shouldn't it be up to the user to decide if to include them?

Yes, I mixed it up with ignore "No Answer", which is automatically removed except option `ignore_no_answer=False` is set.  "I' don't know" is no longer automatically removed.

**Comment by TheFlike** [comment]
> * bar position: I think we only need it for positioning inside a bar group (that's where the total is right?).
> 
>     * 0 count bars: I would not filter them out, might also confuse people. Just add a line that shows that there are basically no answer, but we considered the group.
> 
>     * calculate_aspect_ratio=True, yes should be standard True I would say. We just have to put it clearly in the documentation that if they want to change the fig size, they have to set it to False.
```
s.plot(
    "C3",
    compare_with="A6",
    save='myownfilename.png',
    totalbar=True,
    threshold_percentage=0,
    bar_positions=[-2.5,-1],
    suppress_answers = ["I don't know",'I have administrative problems.'],
    legend_columns=2,
    plot_title="Putting in my own title",
)
```
gives now:
myownfilename

The zero bars can be turned off by setting `show_zeroes=False`

**Comment by lheckmann** [comment]
Sorry - should have specified: I though about adding a horizontal line for the 0% not vertical. Thin enough to not really count, but thick enough to be seen that the space is counted maybe? Can we try?
Then it's also easy to see with the colors which bars are 0.

**Comment by lheckmann** [comment]
And thanks for all the other changes! I'll check them once we have the final update.

**Comment by TheFlike** [comment]
> Sorry - should have specified: I though about adding a horizontal line for the 0% not vertical. Thin enough to not really count, but thick enough to be seen that the space is counted maybe? Can we try? Then it's also easy to see with the colors which bars are 0.
like that?
myownfilename

**Pull request merged**
