### PR TITLE
94 change default filename for comp plots

### PR DESCRIPTION
**Pull request by TheFlike**
## Description

Bug fixes issue 94

Describe your solution:

Added new class `save_plot` to survey.py script which creates `filename` and save path and saves the figure depending on all used questions for creation of the figure.
added variable `legend_sequence`, the legend is now as well displayed in order of the answers of the compare_with question.
changed simple_comparison.py to add automatically extra space after totalbar

everything should work now.

## Checklist

- [x] I created an issue and discussed solutions with others.
- [x] I wrote tests or updated tests regarding my changes.
- [x ] I follow the style guidelines of this project.
- [ x] I have commented my code. So, other can understand what I did.
- [x] I checked if all tests passing after my changes.

## PR review

Anyone in the community is free to review the PR once the tests have passed.

- [ x ] Add labels and milestones to the PR so it can be classified.
- [x] Check that all items from the **checklist** are resolved.
- [x] Is this pull request ready for review?

### CODE REVIEW

**Comment by lheckmann** [comment]
Hi! 
thank you, from functionality it works very well :) 

Just one question (because I did not follow the survey.py structure in detail), how where the figures saved before you added the new function?

**Comment by TheFlike** [comment]
The same way, I only moved out the formulating of the `filename` and the save command from the plot() function and gave it it's own function for lucidity purposes.
I expanded it to add the `compare_with` and `add_questions`
Then I added the dpi choice and the picture type choice which are already standard in pyplot because I thought it might be nice to be able to change resolution or completely go to vectorgraphics so the eval team can use the same function for poster as well as preview pictures or print.

**Comment by lheckmann** [comment]
Yes, I think one can set the dpi with the rc parameters. Do you know if the rc parameters or the one in your function would be dominant?

If it is the second it would be fine, guess it would take the default (the rc one) anyway except for if I specifically add it to the function.

If it is the other way round it might be confusing.

**Comment by TheFlike** [comment]
The one in the function would be dominant,
if you don't set the parameters in the function it will as standard take the parameters from the figure which are set by the theme changes,
if you set the parameters in the function, the saved picture will have the parameters you chose.

**Comment by lheckmann** [comment]
Perfect, than it should be fine and I can approve your PR :)

**Pull request merged**
