### PR TITLE
added a column to bin phd duration month into bins of months

### PR DESCRIPTION
**Pull request by johnlee2104**
@lheckmann I named the new column that bins the phd duration month as `PhD duration category`, if you prefer another name, let me know. :)

### CODE REVIEW

**Comment by lheckmann** [comment]
I tried to use it, but for me it does not add the columns to the df. Also not with the original e.g. months version.
 What I do is:

`dict_trafo = {"phd_duration": ("A8", "A9")}  
s.read_responses(input_path + csv_filename,dict_trafo)  
s.responses['PhD duration (months)']
`
and if gives me
`KeyError: 'PhD duration (months)'`

I also tried in the main branch and there is also does not add it. Am I adding it the wrong way?

And to more things I notices:

- it would be good to only use small letters and no spaces in the variable names (just a convention). So can we do `phd_duration_category`? Similar for the numeric values
- the other transformations are using a syntax of [] not () for two variables. I think it is fine to use () here since you need both question codes to be stated, but we need to make it clear in the wiki when you write the documentation.

**Comment by johnlee2104** [comment]
> I tried to use it, but for me it does not add the columns to the df. Also not with the original e.g. months version. What I do is:
> 
> `dict_trafo = {"phd_duration": ("A8", "A9")} ` `s.read_responses(input_path + csv_filename,dict_trafo) ` `s.responses['PhD duration (months)']` and if gives me `KeyError: 'PhD duration (months)'`
> 
> I also tried in the main branch and there is also does not add it. Am I adding it the wrong way?
> 
> And to more things I notices:
> 
> * it would be good to only use small letters and no spaces in the variable names (just a convention). So can we do `phd_duration_category`? Similar for the numeric values
> * the other transformations are using a syntax of [] not () for two variables. I think it is fine to use () here since you need both question codes to be stated, but we need to make it clear in the wiki when you write the documentation.

Hey Lea, the key `dict_trafo` should be  `{"duration": ("A8", "A9")}`. Can you try it and let me know if it works?

**Comment by lheckmann** [comment]
ah sorry, yes there it works.

Still when doing:

`s.plot("PhD duration category",save=True,totalbar=True)`

I gives an error, can you check which part of the implementation is missing to be able to plot it?

**Comment by lheckmann** [comment]
Also I realized another very annoying thing: It works when using it on the dummy test data but not the real data since the question actually changes. We can discuss later today.

**Comment by lheckmann** [comment]
How is the status @johnlee2104?

**Comment by johnlee2104** [comment]
> 

Sorry for the late reply Lea. I tried to do `git pull` to have the _v2 files that you mentioned but it didn't seem to work. Could you help me please?

**Comment by lheckmann** [comment]
are you doing the pull in your or the main branch?

**Comment by johnlee2104** [comment]
> 

I believe I'm in this current branch `origin/132-categorical_phd_duration`

**Comment by johnlee2104** [comment]
> Okay, now they should also be there in your branch. Can you try again with git pull?

Yes, it works now. Thanks a lot. I will get to fixing the functions now.

**Comment by johnlee2104** [comment]
There are some problems with the test unit. Since I am using the _v2 files now, the test unit won't work because it uses the old version of dummy survey files where column A8a,b and A9a,b do not exist. I am not sure what can I do in this case...

**Comment by fudw** [comment]
Try using the base test case like `class TestLimeSurveyInitialisation(BaseTestLimeSurvey2021Case):` in Line 16 of `test_lime_survey.py`. This way you have full control how to initialise and which structure and data files you read in.

**Comment by johnlee2104** [comment]
Since now the phd start and end time have been each separated into two columns, month and year, I added a dummy date '01' so that I can concat the month and year columns with the dummy date to form a `pd.to_datetime` parsable format, e.g. 2022-07-22. 

Also, some responses have only month and no year while some have year and no month, e.g. start year response being 'I don't want to answer this question' and start month response being '05'. For the case where the months do not have a proper answer, I replace them by the value '01', therefore assuming that they started in January of the year that they filled. I think this can help to rescue some responses, rather than treating them as non-response which will later get parsed into `NaT` by `pd.to_datetime`. Please let me know what you think about this! :)

**Comment by lheckmann** [comment]
Yes I think it is a fine approach. Just I would not put 01 but 06 for the months missing, middle of the year might be a better approximation.
(important to remember to put this in the wiki for documentation)

**Comment by johnlee2104** [comment]
> Yes I think it is a fine approach. Just I would not put 01 but 06 for the months missing, middle of the year might be a better approximation. (important to remember to put this in the wiki for documentation)

I agree with you. Just did and pushed the changes. :)

**Comment by lheckmann** [comment]
Is it already ready for review?

If yes, what is still missing is adding 'phd_duration_category' to the question structure of the limesurvey object. For responses it is already there.

Only 'phd_duration' is in there as defined in L212-216 in survey.py
For how to add it see e.g. 'satisfaction_class' in L220ff.

**Comment by johnlee2104** [comment]
> 

I thought it was ready for review. I don't understand what you mean by adding it to the question structure. Is there anything else to add beside in line 212-216 of survey.py?

**Comment by lheckmann** [comment]
The survey object consists of two structures: once the questions of the survey read in from the xml file and once the responses of the participants read in from the csv file. The first is saved in s.questions, the second in s.responses. 
I think you added the duration only to the responses since I cannot plot it yet. 
Have a look at how it is done for satisfaction in l220 and following.

**Comment by johnlee2104** [comment]
> The survey object consists of two structures: once the questions of the survey read in from the xml file and once the responses of the participants read in from the csv file. The first is saved in s.questions, the second in s.responses. I think you added the duration only to the responses since I cannot plot it yet. Have a look at how it is done for satisfaction in l220 and following.

Hey Lea, can this PR be dealt with later on? I have something important to do today and I don't think I can finish it before you go for summer break anymore... I'm very sorry about that!

**Comment by lheckmann** [comment]
If it's fine with you, I can take it over and do the last changes. Should only be small anyway :)

**Comment by johnlee2104** [comment]
That’d be great, Lea. Thanks a lot! It would also be nice if you could show me which part is missing when you’re back from vacation. Thanks again!

On 23 Jul 2022, at 12:00 pm, lheckmann ***@***.***> wrote:

﻿

If it's fine with you, I can take it over and do the last changes. Should only be small anyway :)

**Pull request merged**
