### PR TITLE
088 alexandra saticfaction score

### PR DESCRIPTION
**Pull request by lexixix**
## Description

I implemented the first calculation for the overall satisfaction score based on branch 96 with some changes for the satisfaction. Unfortunately, I could not fully test the code yet, because I had an error, but i did debug the code and this worked. It may be necessary to add something to make sure it only calculates for C1 questions, since I cannot yet verify that it actually does that.

## Checklist

- [x] I created an issue and discussed solutions with others.
- [ ] I wrote tests or updated tests regarding my changes.
- [x] I follow the style guidelines of this project.
- [x] I have commented my code. So, other can understand what I did.
- [ ] I checked if all tests passing after my changes.

## PR review

Anyone in the community is free to review the PR once the tests have passed.

- [ ] Add labels and milestones to the PR so it can be classified.
- [ ] Check that all items from the **checklist** are resolved.
- [ ] Is this pull request ready for review?

### CODE REVIEW

**Comment by lheckmann** [comment]
Some of the checks above did not pass successfully - which they actually should. @fudw do you know what they check exactly?

**Comment by fudw** [comment]
It looks like the pre-commit hooks for formatting checks were not installed (correctly) in the local environment, hence the code was not checked before the commits were pushed. I'd suggest trying running the following in your terminal:
```bash
pre-commit install
```

I have deleted the empty file and fixed the formatting, but there are two more things that need to be done before this can be merged:

1. Now Line 124 in `test_lime_survey.py` raises an error because Lines 180-194 are added in `survey.py` but the unittests don't know about them. The same dicts should be added to `test_lime_survey.py`, e.g. from Line 112 on. 
2. New tests should be written in `test_lime_transformations.py` for the satisfaction transformations, in a similar fashion to the mental_health and supervision ones. 

If you need help with any of these, we can have a look together on Monday's meeting.

**Comment by lheckmann** [comment]
@lexixix did it resolve today in the meeting?

**Comment by lexixix** [comment]
It has not been resolved yet, but there are some things I wanted to try and I would get back to you, whether that worked.

**Comment by fudw** [comment]
Just in case nobody noticed, the latest commits removed the entire `test_lime_transformations.py` and all the other changes Alexandra originally implemented, so one probably needs to either revert some commits and try the rebasing operation again, where presumably things went wrong.

**Comment by lheckmann** [comment]
Yes thanks! That was on purpose since there was a merge conflict with the main branch that wrapped her functions and the numerical conversions ones together. So she locally still has her scripts in a separate folder and will now add her functions to the updated scripts after the merge with main.

**Comment by fudw** [comment]
It looks like the hooks are still not working properly in your local environment. Are any of you still working on a fix? If not, I can take over and make a commit on my machine. If you are, then please also do a pull for the main and rebase because new changes from another PR have just been merged.

**Comment by lexixix** [comment]
While I might have an idea, what the problem is, I think it would be better if you continue. So I would take your offer to take over.
Please let me know if you need any further information.

**Comment by fudw** [comment]
@lexixix The code from your last commit was actually not functional, and I had to change the keys of the dict ` satisfaction_question_scores` in Lines 383-389 in `transformations.py` from "Fully agree", "Partially agree" etc. to "Very satisfied", "Satisfied" etc.

I don't doubt that you coded the function correctly but suspect that you copied/pasted an older version of the code in one of your final commits. Therefore, can you please double check everything is as originally intended? All I should have changed is formatting (apart from the keys mentioned above).

**Comment by lexixix** [comment]
Yeah, when I re-added the 'satisfaction' back into the files, this confused me a bit as well. But I left it, because I thought I was getting 'betriebsblind' (I don't think there is an English word for that). Thank you for helping, I will check everything.

**Comment by lexixix** [comment]
That's good to hear. :D
I actually cannot remember changing them. Dawei changed them, because I accidentally re-added an older version of the code, but other than that I tried to make them match the supervision categories.

**Comment by fudw** [comment]
> One last question: why did you change the categories from "Very satisfied": 5.0, "Satisfied": 4.0, "Neither/nor": 3.0, "Dissatisfied": 2.0, "Very dissatisfied": 1.0, in the subquestions to "very satisfied", "rather satisfied", "neither satisfied nor dissatisfied", "rather dissatisfied", "very dissatisfied", in the overall satisfaction?

This change was needed to be self-consistent with Lines 219 - 229, which define the overall satisfaction classes:
```python
"satisfaction_class": {
            "label": "What is the satisfaction class?",
            "type": "single-choice",
            "choices": {
                "A1": "very satisfied",
                "A2": "rather satisfied",
                "A3": "neither satisfied nor dissatisfied",
                "A4": "rather dissatisfied",
                "A5": "very dissatisfied",
            },
        },
```

These were written by @lexixix. I didn't give it much thought at the time and simply went with this. I can of course change them to be the same as the subquestion categories, if you think it's better that way.

**Comment by lheckmann** [comment]
Hi,
sorry for the late response (at a conference). I think it would be better to stick with the subquestions since it is closer to what people really answered then (I know, should not make a difference, but still). Would it be fine for you to change it @fudw?

I'll check later if the supervision ones match the subquestions.

**Pull request merged**
