### PR TITLE
129 problems in merged pr 124

### PR DESCRIPTION
**Pull request by TheFlike**
## Description

Repair of a botched pull request

Describe your solution:
removed library typing dict and tuple from survey.py
Deleted commented out code
deleted notebook file

## Checklist

- [x] I created an issue and discussed solutions with others.
- [x] I wrote tests or updated tests regarding my changes.
- [x] I follow the style guidelines of this project.
- [x] I have commented my code. So, other can understand what I did.
- [x] I checked if all tests passing after my changes.

## PR review

Anyone in the community is free to review the PR once the tests have passed.

- [x] Add labels and milestones to the PR so it can be classified.
- [x] Check that all items from the **checklist** are resolved.
- [x] Is this pull request ready for review?

### CODE REVIEW

**Comment by TheFlike** [comment]
This is quite stupid. Black changed a lot of never touched files during running pre-commit first time and then flake8 gave a lot of commit errors (missing whitespace etc) which black should have fixed. No the tests runs in my environment (same as all the time before) but here it gives errors.

**Comment by fudw** [comment]
If you suspect the hooks are not working properly, I'd suggest reverting the commits and remaking the changes you actually want in a new virtual environment and push again.

**Comment by TheFlike** [comment]
Found an easier way, branched out 129... branch to a new branch, deleted one leftover line in one file, git add, pre-commit, black runs on all files and merged back in to 129. I think black does sometimes at the beginning of a new branch control all files and then it adds errors where there are none. weird.

**Comment by fudw** [comment]
Looks good! Thanks for fixing them!

**Pull request merged**
