### PR TITLE
105 adding plot title

### PR DESCRIPTION
**Pull request by NiRuff**
## Description

**Please always create an issue and discuss solutions. Also, link the issue within the description of the PR**

Describe your solution:

- What is this PR for?
Solution for issue 105

- What did you change?
plot_tile argument added for the plot functions to plot the question as title if plot_title == True (default), no title if plot_title==False or a custom title if plot_title is some string

- Is there any problem/issue/workaround within your code (e.g. hacky or slow code)?
no

- Did you had any problems/questions you solved by your own?
Some likert plots have the legend hard-coded on top of the plot. Consequently, for likert plots I had to adjust the height of the title, so that it won't overlap.

The functionality can be tested with the following code derived from the usage example:
```
# Imports
from n2survey import LimeSurvey
%matplotlib inline
# Read the structure file
s = LimeSurvey("./Leibniz Results - N2 survey/survey_275333_en.xml")

# Read responses
# NOTE: Responses are provided in CODES only
s.read_responses("./Leibniz Results - N2 survey/results-survey275333.csv")

# Plot a question
s.plot("B6", plot_title="my own title")

# Plot a question and save it
s.plot("A1", save=True, plot_title=False)

# Plot a question and save it
s.plot("A1", save=True, plot_title=True)
```
## Checklist

- [x] I created an issue and discussed solutions with others.
- [x] I wrote tests or updated tests regarding my changes.
- [x] I follow the style guidelines of this project.
- [x] I have commented my code. So, other can understand what I did.
- [x] I checked if all tests passing after my changes.

## PR review

Anyone in the community is free to review the PR once the tests have passed.

- [x] Add labels and milestones to the PR so it can be classified.
- [x] Check that all items from the **checklist** are resolved.
- [x] Is this pull request ready for review?

### CODE REVIEW

**Comment by lheckmann** [comment]
@NiRuff can you figure out why your test are failing?
And then maybe @TheFlike you would be good as a reviewer since you know the plotting best?

**Comment by TheFlike** [comment]
https://github.com/N2-Survey/SurveyFramework/issues/105#issuecomment-1135792002

and of course I can do the review if the pre-commit hooks work (see linked answer)

**Comment by j-pietsch** [comment]
@NiRuff,
I think you might have uploaded/pushed the Leibniz results in your current pull request.
I was kind of confused by the almost +30.000 changed lines of code!

I might be wrong, but I would assume that this happenend by accident ;)

**Comment by TheFlike** [comment]
I am wondering why there was a change in the structure.py file.
I never worked with that one and I don't think it should be changed.
Could the reason here be the usage of python lower then V3.9 (anaconda uses still some form of 3.8 if not specified while creating the environment)?
Everything else seems fine for me.

**Comment by NiRuff** [comment]
Hey,

in this structure.py nearly everywhere the types are used that are imported from the _typing_ module.
However, in these two lines e.g. **dict** was used instead of the imported **Dict**, which leads to errors in python <3.9.
Having it uppercase ensures the usage from typings and is consistent with all other definitions of function types throughout the whole script.
In Python >= 3.9 both work, however, it is still inconsitent with the other function definitions in this script.
So the changes in the two lines here made the code work in Python 3.8.x and ensured consistency in function definition thorughout the script (by using the types from the typings module everywhere).

But if you prefer I can also delete these changes.

Best,
Nicolas

**Comment by TheFlike** [comment]
Maybe @fudw or @rguliev can answer that, they are way longer on the project then I am and this fix came up a couple of times already and it was always said to leave it only working for 3.9, but why, I don't know.

**Comment by fudw** [comment]
@TheFlike is correct. It was decided to go with the 3.9 built-in convention instead of explicitly importing the types from the `typing` module. It would be great if you can follow the same convention in your code too. Ideally, one should have set up the virtual environment with 3.9 anyway.

**Comment by rguliev** [comment]
Hi,

@NiRuff has a good point. In fact, importing from the `typing` module has legacy reasons but then it was decided to keep it for compatibility with python < 3.9 (just in case) and to save time for a more important part of the code. The problem is that we did not choose a standard for typing in the project, so you might find inconsistent places.
I think it is a good idea to bring everting to a standard format. Feel free to change it. Which one to use `dict` or `Dict`? Well, I would go for the one that will require less code rewriting.

**Comment by NiRuff** [comment]
Just for clarification - you import from typings everywhere except for these two lines of code - that's why I considered that inconsistent and changed it in my codefor the structure.py, but if you prefer I can just not commit these changes and keep it in the old (inconsistent) version - it does not change any functionality of my changes except for the whole project only runing on Python >3.9.

If it should be consistent, someone needs to either import from typings everywhere (what I present here) or not import from typings anywhere (which would be more work)

For now if you prefer I can remove the structure.py from the commit. I just need a clear answer for that.
Rustam's comment (that I can not see right now but got via mail) e.g. seemed like keeping these changes.
Thanks!

**Comment by fudw** [comment]
As far as I can see, the data types `list`, `tuple` etc. are present in native python since 3.9, and importing them from `typing` is deprecated (see https://stackoverflow.com/questions/66540017/whats-the-best-practice-of-typing-hint-after-python-3-9). However, we import `Union` and `Optional` from typing because they are not available in 3.9. If we at some point go to 3.10, then there are native functionality to replace `typing.Union` and `typing.Optional` too (see https://stackoverflow.com/questions/69440494/python-3-10-optionaltype-or-type-none), which will eliminate the need for any instance of `import typing`. But that is for another day.

**Comment by TheFlike** [comment]
Aha, I never knew that, I also imported from typing, but the reason was that I just looked at previous older parts and everyone else seemed to do it, so I just tried to mirror everything as good as possible, without grasping the whole framework. (Not a real programmer here)

So, if I understand it correctly, typing is no longer necessary from python 3.9 onward.
This means the library typing will probably not be maintained for the future. 
Even if this at the moment does not make any difference,  I'd conclude we live with the inconsistency until somebody finds time to remove typing from everywhere it has been used.

It is also a good test to find out quickly if somebody did not set up a proper environment and did not follow the readme.
So if people go step by step with the manual they should not have any problems.

So I'd say please revert and sorry for the inconvenience.

**Comment by fudw** [comment]
If you are having issues reverting a specific file to an earlier commit, give this a try: https://github.com/N2-Survey/SurveyFramework/pull/119#discussion_r893635735

**Comment by TheFlike** [comment]
@NiRuff yeah, your work should definitively come first, there is no shame in recognizing that this free project takes more time then expected. At least you tried, which is more then half of the original some 20 people that said they'd help out did, and they are not at fault for that either.
It is free work and we are happy for every help we get. Hope you have fun on the conference.
I'll merge the pull request now.

**Comment by NiRuff** [comment]
Thanks for taking over! :)

**Comment by fudw** [comment]
This PR shouldn't have been merged as there were a couple of issues yet to be corrected, including some of the changes made to `survey.py`. 

1. The imports of `Dict` and `Tuple` and subsequent replacements should have been reverted, as discussed yesterday. 
2. There are a number of code blocks commented out but are not actually comments, e.g. Lines 862 - 863 and several more. Delete them if not needed and don't leave them in as comments. 
3. A notebook file is added, but there is no mentioning of it in the PR description or the originally issue as far as I can see. If this was intended, explain what it is and why it is added. If it's not specifically related to the original issue, it's good practice to leave it out as a separate issue and PR.
4. The merging was done with "Create a merge commit" rather than "Squash and merge". The former messes up the commit hsitory of the main branch with individual commits from the feature branch, while the latter packs all commits from the feature branch together into a single commit into main and is much easier to inspect and manage. I made the same mistake the first time, but please don't do it again.

@TheFlike Do you think you can correct these things if I create a new issue?

**Pull request merged**
