### PR TITLE
19 plots for comparing distributions

### PR DESCRIPTION
**Pull request by j-pietsch**
## Description

New functionality is added to plot numeric questions ( "B1b", "B2", "B3", "B4", "B10", "C4", "C8") which are filtered before plotting. The numerical question can be filtered using a dictionary with keys as single-choice questions and values as the answers to these single-choice questions (see following or next comment for more information).

_Possible function calls for single comparison:_
`s.plot_numeric_comparison("B2", {"A6": ["A1", "A3"], "A7": ["A1", "A2", "A3", "A4"]})`
`s.plot_numeric_comparison("B2", {"A6": "all"})`

_Possible function calls for multiple comparisons:_
`s.plot_numeric_comparison("B2", {"A6": ["A1", "A3"], "A7": ["A1", "A2", "A3", "A4"]}, simple_filtering=False)`

Describe your solution:

- Resolves issue #19 
- Added new file `plot/plot_numeric_comparison.py` for plotting
- `lime/survey.py`:
   - Added new function `plot_numeric_comparison` (as well as helper function `filter_responses`)
   - `count` method accepts additional input `responses: pd.DataFrame` which is necessary for couting filtered DataFrames
- Filtering of DataFrame is done, DataFrame entries are counted and appended to list
- List can have a maximum of 9 entries to fit into one plot (with maximum of 9 subplots)
- Calculation of median from transformed questions and showing of median in figure
- Adjustable parameters for the plotting:
    - color scheme
    - figure size
    - displaying the question title
    - displaying a subplot for the unfiltered data
    - displaying 'No answers'
    - displaying percentages above bars (and hiding percentages below specific threshold)
    - displaying median

## Checklist

- [x] I created an issue and discussed solutions with others.
- [x] I follow the style guidelines of this project.
- [x] I have commented my code. So, other can understand what I did.
- [x] I checked if all tests passing after my changes.

## PR review

Anyone in the community is free to review the PR once the tests have passed.

- [x] Add labels and milestones to the PR so it can be classified.
- [x] Check that all items from the **checklist** are resolved.
- [x] Is this pull request ready for review?

### CODE REVIEW

**Comment by j-pietsch** [comment]
## Code examples for checking
`s.read_responses("./data/dummy_data_2021_codeonly.csv", transformation_questions={"range": ["B2", "B3", "B4", "B10", "C4", "C8"],},)`

`s.plot_numeric_comparison("B2", {"A6": ["A1", "A3"], "A7": ["A1", "A2", "A3", "A4"]}, display_percents=True, save=True, display_no_answer=False,)`
Numeric_simple_comparison_B2_with_A6_A7

`s.theme["palette"] = "Reds"`
`s.plot_numeric_comparison("B3", {"A6": ["A1", "A3"], "A7": ["A1", "A2", "A3", "A4"]}, simple_filtering=False, display_percents=True,
save=True,
display_no_answer=False,
)`
Numeric_multiple_comparison_B3_with_A6_A7

`s.theme["palette"] = "tab10"`
`s.plot_numeric_comparison("B4",
{"A6": ["A1", "A3"], "A7": ["A1", "A2"]},
display_no_answer=False,
save=True,
display_median=True,
y_axis_max=[20,20,20,20,20]
)`
Numeric_simple_comparison_B4_with_A6_A7

`s.plot_numeric_comparison(
"B10",
{"A6": ["A1", "A3"], "A7": ["A1", "A2", "A3", "A4"]}, display_percents=True,
percent_threshold=10,
save=True,
display_no_answer=False,
)`

Numeric_simple_comparison_B10_with_A6_A7

**Comment by fudw** [comment]
A number of changes have been made to the main branch. Please wait until PR #120 has been merged by Lea, pull and rebase and resolve any conflicts before merging this PR.

**Comment by lheckmann** [comment]
PR120 is merged, please follow Dawei's instructions above. I'll have a look at the new functionalities in between.

**Comment by lheckmann** [comment]
It looks really nice now, thank you!

Here my comments:

- can we hide the plot_numeric_comparison() in the background and have the user use the normal plot() function? And the if there is a numeric value involved it calls the plot_numeric_comparison()? That's how we did it for all plotting functions now.
-  If I run `s.plot_numeric_comparison( "B10", {"A6": "all"}, simple_filtering=False, display_unfiltered_data=False)`, I get the errors below. I think the problem is the option `simple_filtering=False` what does it exactly do?

> ---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [30], in <module>
----> 1 s.plot_numeric_comparison("B10", {"A6": "all"}, simple_filtering=False, display_unfiltered_data=False)

File ~/Dokumente/PhDNet/PhDSurvey2021/SurveyFramework/n2survey/lime/survey.py:1226, in LimeSurvey.plot_numeric_comparison(self, question, questions_to_filter, simple_filtering, valid_questions, display_title, display_unfiltered_data, display_no_answer, display_median, display_percents, fig_size_inches, save, **kwargs)
   1224 label = "multiple"
   1225 first_key, first_values = list(questions_to_filter.items())[0]
-> 1226 second_key, second_values = list(questions_to_filter.items())[1]
   1227 # Multiple comparisons only done for: - max. 2 `questions_to_filter`
   1228 if len(questions_to_filter.keys()) != 2:

IndexError: list index out of range

**Comment by j-pietsch** [comment]
- Yes, should be possible. However, variables have to be renamed and the code has to be adjusted accordingly. Some parameters in `plot` are also currently not used by `plot_numeric_comparison`. Maybe we can use this preliminary functionality at first and create a new issue for the integration of `plot_numeric_comparison` in `plot` as I won't have time this week.
- Yes, you are correct, thanks for spotting! `simple_filtering=False` requires two different quesitons in  `questions_to_filter`. Cases like the one you provided will now be handled with a `NotImplementedError`.


**Examples:**
`simple_filtering=True` : performs filtering for each answer possibility separately
`simple_filtering=False`: performs multiple filtering combining the answer possibilities from two questions

like the following:
`questions_to_filter: {'gender': ['male', 'female'], 'nationality': ['German', 'Non-German']}`

`simple_filtering=True` : 4 possibilities ['male', 'female', 'German', 'Non-German']
`simple_filtering=False` : 4 possibilities: ['male'+'German', 'female'+'German', 'male'+'Non-German', 'female'+'Non-German']


Also facing some issues trying to rebase the current branch to main.

**Comment by lheckmann** [comment]
I'm fine with using it as a preliminary functionality yes! And for the functionalities in plot not used by plot_numeric: that is fine, also for some of the other option. You just have to fill the wiki accordingly so that people know which functionalities they have using plot_numeric.

And thanks for fixing the simple_filtering, makes sense now.

Did you manage to rebase the branch now? Then I can merge it.

**Comment by j-pietsch** [comment]
@lheckmann The branch is now rebased and can be merged imo. I will
- fill out the wiki (with the preliminary functionality of `plot_numeric_comparison`)
- create a new issue to integrate `plot_numeric_comparison` into the `plot` functionality

**Pull request merged**
